Docs/restructure
iotaledger/wallet.rs pull request #1192
Opened 2022-06-17 15:29 UTC by aleksei-korolev

# Description of change

Restructure the documentation to the new guidelines.

## Links to any relevant issues

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Fix

## How the change has been tested

Local wiki setup, and I clicked through links.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-06-17 15:30 UTC, aleksei-korolev commented
@lucas-tortora @Dr-Electron

2022-06-20 08:49 UTC, Dr-Electron requested changes
Guess you can remove `./tutorials/README.md`, `./internal/README.md` and update `./README.md`. Also let's move `charts.pptx` one folder up. Maybe create a folder like `./resources` and but it in there?

2022-06-20 12:16 UTC, Dr-Electron approved these changes, later dismissed
Lgtm

2022-06-20 15:10 UTC, lucas-tortora requested changes
Just 1 small comment, other than that this LGTM! :)

2022-06-20 15:10 UTC, lucas-tortora commented on documentation/docs/getting_started/python.md
> +## Securityhttps://wiki.iota.org/chrysalis-docs/guides/backup_security
I think this link may be misplaced or malformatted.

2022-06-20 15:15 UTC, lucas-tortora submitted a review, later dismissed

2022-06-20 19:12 UTC, Dr-Electron requested changes

2022-06-20 19:12 UTC, Dr-Electron commented on documentation/docusaurus.config.js
> +  onBrokenLinks: 'warn',
You can remove this. The wiki will do it

2022-06-21 21:21 UTC, Dr-Electron requested changes
Looks good to me.

One last thing.
Can you move the `chart.pptx` file into `documentation/resources/charts.pptx`?

2022-06-22 13:43 UTC, Thoralf-M commented on documentation/docs/reference/python.md
Not related to this change, but there is 
```
node = {
    'url': string,
    'auth': [NodeAuth](#nodeauth) (optional),
}
```
which should be 
```
node = {
    'url': string,
    'auth': [NodeAuth](#nodeauth) (optional),
    'disabled': bool,
}
```
could you update this in this PR?

2022-06-22 16:48 UTC, Thoralf-M commented on documentation/docs/reference/python.md
Thanks :heart:

2022-06-22 17:04 UTC, Thoralf-M reviewed
For what does `documentation/docs/tutorials/.keep` exists?

2022-06-23 09:14 UTC, aleksei-korolev commented
> For what does `documentation/docs/tutorials/.keep` exists?

Too keep the folder in git to make it clearer where to put tutorials once we have some.

2022-06-23 09:19 UTC, Thoralf-M approved these changes

2022-06-23 09:49 UTC, Dr-Electron requested changes

2022-06-23 09:49 UTC, Dr-Electron commented on documentation/sidebars.js
>  };
```suggestion
};

```

New line. Please. I can't see this GitHub symbol for missing new lines anymore :trollface:

2022-06-27 12:55 UTC, thibault-martinez approved these changes

2022-06-27 13:01 UTC, merged