Add option to sync only basic outputs with AddressUnlockCondition
iotaledger/wallet.rs pull request #1239
Opened 2022-06-30 11:43 UTC by Thoralf-M

# Description of change

Add option to sync only basic outputs with AddressUnlockCondition, could be useful for exchanges or others who don't want to handle the other unlock conditions and output types

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Modified example

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-06-30 11:46 UTC, Thoralf-M commented on src/account/operations/syncing/addresses.rs
> +        // Only sync outputs with basic unlock conditions and only `AddressUnlockCondition`
```suggestion
        // Only sync basic outputs with an `AddressUnlockCondition` and no other UnlockConditions
```

2022-06-30 12:09 UTC, thibault-martinez approved these changes, later dismissed

2022-07-04 07:21 UTC, samuel-rufi requested changes

2022-07-04 07:21 UTC, samuel-rufi commented on src/account/operations/syncing/options.rs
>      0
maybe create some constant and return it here instead?  also for the other functions above^

2022-07-04 08:59 UTC, thibault-martinez approved these changes

2022-07-04 09:39 UTC, samuel-rufi approved these changes

2022-07-04 09:46 UTC, merged