Only do a single consolidation transaction
iotaledger/wallet.rs pull request #1437
Opened 2022-09-15 12:33 UTC by Thoralf-M

# Description of change

Only do a single consolidation transaction

## Links to any relevant issues

Related to #1417 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-09-15 12:47 UTC, samuel-rufi approved these changes, later dismissed

2022-09-15 13:05 UTC, thibault-martinez requested changes
There is a warning at compilation

2022-09-15 13:22 UTC, thibault-martinez approved these changes

2022-09-16 07:29 UTC, samuel-rufi approved these changes

2022-09-16 07:31 UTC, merged