Fix prepare output for nfts
iotaledger/wallet.rs pull request #1543
Opened 2022-11-04 11:02 UTC by Thoralf-M

# Description of change

Allow new nft output creationg, use minimum required storage deposit for nfts

## Links to any relevant issues

#1540 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Not tested yet

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-11-04 11:03 UTC, Thoralf-M commented on src/account/operations/transaction/prepare_output.rs
> -                            // or unlock conditions
Not sure if the comment was wrong or the amount should be higher

2022-11-07 11:35 UTC, samuel-rufi approved these changes, later dismissed

2022-11-07 11:50 UTC, Thoralf-M commented on src/account/operations/transaction/prepare_output.rs
> -                            // or unlock conditions
The additional amount gets added later if needed

2022-11-07 12:09 UTC, samuel-rufi approved these changes, later dismissed

2022-11-07 12:19 UTC, thibault-martinez requested changes
Changelog entry

2022-11-07 13:17 UTC, thibault-martinez commented on CHANGELOG.md
> +- `IssuerFeature` and `SenderFeature` to `prepare_output()` options argument;
Sorry I'm being super picky here but can you put added before changed please ?

2022-11-07 13:43 UTC, thibault-martinez approved these changes

2022-11-07 13:43 UTC, Tuditi approved these changes
LGTM! :+1:

2022-11-07 13:48 UTC, merged