Change sync options
iotaledger/wallet.rs pull request #1737
Opened 2023-01-18 13:19 UTC by Thoralf-M

# Description of change

Change sync options so the user has more control over what gets synced or not.
Now one can sync NFTs owned be the account addresses, but don't sync basic, alias or other NFT outputs owned by them.

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Modified Rust and Nodejs examples

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-01-20 16:56 UTC, thibault-martinez requested changes
Conflicts

2023-01-23 08:45 UTC, thibault-martinez commented on src/account/operations/syncing/addresses/output_ids/mod.rs
> +                            .get_alias_and_foundry_output_ids(&bech32_address, sync_options.clone())
Is this clone necessary ? It's already been cloned

2023-01-23 08:52 UTC, thibault-martinez approved these changes

2023-01-23 09:10 UTC, samuel-rufi approved these changes

2023-01-23 09:58 UTC, merged