(bindings/java) Updated MigrationEvent
iotaledger/wallet.rs pull request #597
Opened 2021-04-28 22:15 UTC by kwek20

Was broken, no longer is broken ⚡

2021-04-29 16:33 UTC, kwek20 commented
@lucasfernog

2021-04-29 17:57 UTC, lucasfernog requested changes

2021-04-29 17:57 UTC, lucasfernog commented on bindings/java/native/src/classes/event_listener/event_manager.rs
> +pub struct FetchingMigrationData {
we should use getset::CopyGetters here like we do on another places

2021-05-07 20:30 UTC, Thoralf-M approved these changes

2021-05-08 06:36 UTC, rajivshah3 approved these changes

2021-05-08 06:38 UTC, merged