New nodejs binding using the wallet message system and latest neon version.
iotaledger/wallet.rs pull request #674
Opened 2021-06-28 12:27 UTC by melatron

# Description of change

Nodejs binding implementation using the latest neon version and its newest "napi-6". Also using the wallet.rs message system. Everything is similar to how we use the binding in Firefly.

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Tried all the examples that were written for the old nodejs binding.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2021-08-05 11:24 UTC, laumair commented
@melatron I think it is best to remove all logs from examples.

2021-08-05 11:37 UTC, laumair commented
I would suggest using [JSDoc](https://jsdoc.app/tags-example.html) for all methods and classes. 

[iota.js](https://github.com/iotaledger/iota.js/tree/legacy/iota.js/packages/core/src) has some very good references for it.

2021-08-05 11:39 UTC, laumair requested changes

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/tsconfig.json
> +  }
Missing new line

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/examples/binding_example/1-create-account.js
> +    } catch (e) { }
Probably best to at least log the error here.

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/Cargo.toml
> +log = "0.4"
Missing new line

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/examples/binding_example/1-create-account.js
> +// require('dotenv').config()
Is this unnecessary?

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/examples/binding_example/2-generate-address.js
> +run()
New line missing

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/examples/binding_example/2-generate-address.js
> +run()
New line missing

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/examples/message_examples/5-backup.js
> +run()
Missing new line

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/lib/binding/account.js
> +let {
Not sure we are reassigning these, so should preferably be using `cosnt`

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/lib/messages/account.js
> +      id: "1",
Imo, we should remove the ids. They are not needed atm.

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/lib/typings/index.d.ts
> +// export declare enum MessageType {
Why did we comment them out?

2021-08-05 11:39 UTC, laumair commented on bindings/nodejs-async/lib/utils.js
> +module.exports.RemainderValueStrategy = new RemainderValueStrategy();
Missing new line

2021-08-20 08:13 UTC, Thoralf-M commented on bindings/nodejs/src/lib.rs
> +#![allow(clippy::unnecessary_wraps)]
Is there a reason to leave this here?

2021-08-20 08:19 UTC, Thoralf-M commented on bindings/nodejs/Cargo.toml
> +iota-client = { git = "https://github.com/iotaledger/iota.rs", rev = "57c5a33d83be4b8286a54156e9f0d2ac4345e9b9", features = ["mqtt"] }
That's only used for the logger I think, would be better to only import bee-common then

2021-08-20 08:20 UTC, Thoralf-M commented on bindings/nodejs/Cargo.toml
> +bee-message = "0.1.1"
I think we should only use 0.1

2021-08-20 08:20 UTC, Thoralf-M commented on bindings/nodejs/Cargo.toml
> +bee-message = "0.1.1"
```suggestion
bee-message = "0.1"
```

2021-08-20 08:22 UTC, Thoralf-M commented on bindings/nodejs/README.md
> +> require('.').hello()
This should be removed?

2021-08-20 08:25 UTC, Thoralf-M commented on bindings/nodejs/lib/binding/syncedAccount.js
> +const addon = require('../../index.node');
Is this import needed here?

2021-08-20 08:26 UTC, Thoralf-M commented on bindings/nodejs/lib/index.js
> +// todo remove this
needs to be removed

2021-08-20 08:27 UTC, Thoralf-M commented on bindings/nodejs/lib/index.js
> +// const mh = require("./messages/messageHandler.js");
Can we export both things at the same time so one doesn't need to uncomment one?

2021-08-20 08:30 UTC, Thoralf-M commented on bindings/nodejs/lib/messages/accountManager.js
> +const _id = "1";
Unused variable, can be removed?

2021-08-20 08:30 UTC, Thoralf-M commented on bindings/nodejs/lib/messages/messageHandler.js
> +console.log(utils);
```suggestion
```

2021-08-20 08:32 UTC, Thoralf-M commented on bindings/nodejs/src/classes/message_handler.rs
> +const DUMMY_ID: &str = "1";
Please add a comment why this is needed

2021-08-20 08:35 UTC, Thoralf-M commented on bindings/nodejs/src/lib.rs
> +    map.insert(id.clone(), Arc::new(RwLock::new(synced_account)));
Shouldn't we check if the id is already used? I know the probability for this to happen is very low, but not impossible

2021-08-20 08:36 UTC, Thoralf-M commented on bindings/nodejs/src/types.rs
> +
```suggestion
```

2021-08-20 08:37 UTC, Thoralf-M commented on bindings/nodejs/test-database/db/CURRENT
> +MANIFEST-000003
The whole test-database folder should be deleted?

2021-08-20 08:38 UTC, Thoralf-M commented on src/account/mod.rs
> +impl<'de> Deserialize<'de> for AccountIdentifier {
Why didn't it work with the derived Deserialize?

2021-08-20 08:40 UTC, Thoralf-M commented on bindings/nodejs/examples/binding_examples/2-generate-address.js
> +    // console.log('Account:', account.alias())
```suggestion
    console.log('Account:', account.alias())
```

2021-08-23 09:04 UTC, Thoralf-M commented on bindings/nodejs/lib/binding/syncedAccount.js
> +const addon = require('../../index.node');
```suggestion
```

2021-08-23 09:17 UTC, Thoralf-M commented on bindings/nodejs/examples/binding_examples/7-events.js
> +    console.log("Setting stronghold password.");
```suggestion
```

2021-08-23 09:18 UTC, Thoralf-M commented on bindings/nodejs/examples/binding_examples/7-events.js
> +    console.log(process.env.SH_PASSWORD)
```suggestion
```

2021-08-23 09:59 UTC, Thoralf-M commented on src/account/mod.rs
> +impl<'de> Deserialize<'de> for AccountIdentifier {
"it won't work, because it won't Deserialize the correct enum value"

2021-08-23 11:13 UTC, Thoralf-M commented on bindings/nodejs/src/classes/account/mod.rs
> +    Ok(cx.number(receiver.recv().unwrap() as f64))
Shouldn't this be an u64?

2021-08-23 11:14 UTC, Thoralf-M commented on bindings/nodejs/src/classes/account/mod.rs
> +    // let account_wrapper = Arc::clone(&&cx.argument::<JsBox<Arc<AccountWrapper>>>(cx.len() - 2)?);
```suggestion
```

2021-08-23 11:15 UTC, Thoralf-M commented on bindings/nodejs/src/classes/account/mod.rs
> +    Ok(cx.number(receiver.recv().unwrap() as f64))
Same here, shouldn't this be an u64?

2021-08-23 11:16 UTC, Thoralf-M commented on bindings/nodejs/src/classes/account/mod.rs
> +        MessageId::from_str(cx.argument::<JsString>(0)?.value(&mut cx).as_str()).expect("invalid message id length");
```suggestion
        MessageId::from_str(cx.argument::<JsString>(0)?.value(&mut cx).as_str()).expect("invalid message id");
```

2021-08-30 12:30 UTC, laumair approved these changes

2021-08-30 13:13 UTC, Thoralf-M approved these changes

2021-08-30 22:45 UTC, rajivshah3 commented on bindings/nodejs/package.json
> +    "license": "MIT",
```suggestion
    "license": "Apache-2.0",
```
Just realized it said `MIT` before this PR, but it should match the license of `wallet.rs`

2021-08-30 22:45 UTC, rajivshah3 commented on bindings/nodejs/package.json
> -    "prebuild": "^10.0.1"
Are we no longer providing prebuilt binaries?

2021-08-31 12:44 UTC, merged